### ISSUE TITLE
Unable to get example files and model to create

### ISSUE THREAD

**Issue by MaheshMaharana** [project-pareto/pareto-ui#3]
Hi there,
I am able to run the UI but it says no scenarios is selected and when I click on create scenarios, I am selecting few excel files from Project-Pareto Case study.
Its creating the scenario from the case study files but when I am clicking on create model, I am getting error stating that  example_results_dict.json file is missing means its not able to create model for my file.

I request you to kindly include the example file json and dataset so that we can view what is mentioned in the docs and website as dashboard, charts and all..

If you can't make this public then please send the same to my email ID mahesh.maharana@digitalglyde.com...

Thank you...

**Comment by MichaelPesce** [comment]
[small_strategic_case_study.xlsx](https://github.com/project-pareto/pareto-ui/files/9455068/small_strategic_case_study.xlsx)

Hi Mahesh,
Sorry if it wasn't clear, but the UI is still a work progress. It's not set to be released for a couple months, so the functionality and display are still very limited.

That being said, if you are able to install and run the current UI, I've attached an example input excel sheet that you should be able to upload and run the model with.

**Comment by MaheshMaharana** [comment]
Thank you Micheal,
Really Appreciate the efforts you all are making and looking forward to see this in action.
Mean while when I am using the xlsx file to upload and try to run the model with it, I am getting backend error that file not exist and UI error of data inconsistency.

Backend error on Model run
2022-08-31 10:13:40,817 [INFO] app.routers.scenarios: **unable to find and run given excel sheet**

Then it goes to exception and searches for example_dict.json file which doesn't exist in project..
**results_dict = json.load(open('../data/example_results_dict.json'))**

Please let me know if its is too early for asking this questions as I am also trying different things to check out as a developer and interested in what you all are doing in this project.. 

Thank you once again..

**Comment by MaheshMaharana** [comment]
Hi Michael,

Thank you for your response.. I have figured out that it was the solver issue in Project-Pareto module.
`opt = get_solver("gurobi_direct", "gurobi", "cbc")`

I was using gruobi without license and I think it gave error because of that.. When I removed "gruobi" and kept only "cbc" everything worked and I was able to see the model.

Code I used was as below:-
`opt = get_solver("cbc") `

So I think if you can keep this as optional and ask user to select what solver to use...

Anyways thank you and really appreciate what you are doing..
